# Generated by Django 3.1.4 on 2021-01-01 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSubmissionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CodeTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('code_submission_types', models.ManyToManyField(to='web.CodeSubmissionType')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('code_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.codetask')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.codesubmissiontype')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionTestResultType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CA', 'Correct Answer'), ('WA', 'Wrong Answer'), ('EE', 'Execution Error'), ('UT', 'Unknown')], default='Unknown', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TaskTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField()),
                ('expected_output', models.TextField()),
                ('code_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.codetask')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionTestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_output', models.TextField()),
                ('actual_output', models.TextField()),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('execution_memory', models.FloatField(blank=True, null=True)),
                ('task_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.tasktest')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.submissiontestresulttype')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_retest', models.BooleanField(default=False)),
                ('total_score', models.IntegerField()),
                ('code_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.submission')),
            ],
        ),
    ]
