# Generated by Django 3.1.4 on 2021-01-02 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('code_tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('is_processed', models.BooleanField(default=False)),
                ('code_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_tasks.codetask')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_tasks.codesubmissiontype')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionTestResultType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CA', 'Correct Answer'), ('WA', 'Wrong Answer'), ('EE', 'Execution Error'), ('UT', 'Unknown')], default='Unknown', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionTestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_output', models.TextField()),
                ('actual_output', models.TextField()),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('execution_memory', models.FloatField(blank=True, null=True)),
                ('task_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_tasks.tasktest')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submissions.submissiontestresulttype')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_retest', models.BooleanField(default=False)),
                ('total_score', models.IntegerField()),
                ('code_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submissions.submission')),
            ],
        ),
    ]
