# Generated by Django 3.1.4 on 2021-01-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='is_processed',
        ),
        migrations.AddField(
            model_name='submission',
            name='processing_state',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('ENQUEUE_FOR_PROCESSING', 'ENQUEUE_FOR_PROCESSING'), ('PROCESSED', 'PROCESSED')], default='NOT_STARTED', max_length=22),
        ),
    ]
