# Generated by Django 3.1.4 on 2021-01-02 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_submissiontestresult_submission_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissiontestresult',
            old_name='type',
            new_name='test_result_type',
        ),
    ]
