# Generated by Django 3.1.4 on 2021-01-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0009_auto_20210107_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='processing_state',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('ENQUEUE_FOR_JUDGING', 'ENQUEUE_FOR_JUDGING'), ('JUDGED', 'JUDGED'), ('JUDGING_IN_PROGRESS', 'JUDGING_IN_PROGRESS')], default='NOT_STARTED', max_length=19),
        ),
    ]
