# Generated by Django 3.1.4 on 2021-01-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0013_auto_20210123_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiontestresult',
            name='is_zero_test',
            field=models.BooleanField(default=False),
        ),
    ]
