# Generated by Django 3.1.4 on 2021-06-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0014_submissiontestresult_is_zero_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissionsimilarity',
            options={'verbose_name_plural': 'submission similarities'},
        ),
        migrations.AddField(
            model_name='submissionsimilarity',
            name='levenshtein_distance_similarity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
