# Generated by Django 3.1.4 on 2021-06-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0016_auto_20210627_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='processing_state',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('ENQUEUE_FOR_JUDGING', 'ENQUEUE_FOR_JUDGING'), ('JUDGING_IN_PROGRESS', 'JUDGING_IN_PROGRESS'), ('JUDGED', 'JUDGED')], default='NOT_STARTED', max_length=19),
        ),
    ]
