FROM centos
RUN yum update -y && yum install -y \
    python3 \
    python3-pip

## for apt to be noninteractive
ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true

RUN yum update -y && yum install -y \
    php \
    php-cli

RUN ln -s /usr/bin/python3 /usr/bin/python
