# Generated by Django 3.1.4 on 2021-01-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_tasks', '0003_auto_20210105_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codetask',
            name='description_html',
            field=models.TextField(blank=True),
        ),
    ]
