# Generated by Django 3.1.4 on 2021-01-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_tasks', '0007_auto_20210107_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number_representation', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'difficulties',
            },
        ),
    ]
