# Generated by Django 3.1.4 on 2021-01-09 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_tasks', '0008_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='codetask',
            name='difficulty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='code_tasks.difficulty'),
            preserve_default=False,
        ),
    ]
