# Generated by Django 3.1.4 on 2021-01-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_tasks', '0009_codetask_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codetask',
            name='category',
        ),
        migrations.AddField(
            model_name='codetask',
            name='categories',
            field=models.ManyToManyField(to='code_tasks.CodeTaskCategory'),
        ),
    ]
