# Generated by Django 3.1.4 on 2021-01-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_tasks', '0011_auto_20210121_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktest',
            name='is_zero_test',
            field=models.BooleanField(default=False),
        ),
    ]
