# Generated by Django 3.1.4 on 2021-07-03 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_tasks', '0013_remove_codetask_description_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codetask',
            name='description_html',
        ),
    ]
