# Generated by Django 3.1.4 on 2021-07-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_tasks', '0014_remove_codetask_description_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='codetask',
            name='description_html',
            field=models.TextField(blank=True),
        ),
    ]
